# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Terminal"
license = "MIT"
licenselink = "https://github.com/SMontague29/scottmontague/blob/master/themes/terminal/LICENSE.md"
description = ""
homepage = "https://www.scottpmontague.com/"
tags = []
features = []
min_version = "0.21"

[author]
  name = "Scott Montague"
  homepage = "https://www.scottpmontague.com/"
